# WARNING!!!! Nothing in this file is guaranteed to be best practice 
# or even good practice 
# Certain commands may be redundant; this is a play by play of what i did to compile
# the Linux kernel after cloning from https://github.com/torvalds/linux
# and then switching the 6.9.9 branch

# for this example, the linux kernel source is located right in the home directory
# in ~/linux-stable/ . All the configs generated by the commands will end up somewhere
# in this folder, as well

# i'm nearsighted, and using this thing on the left side of the screen,
# so I press Enter a lot :)

# if you end up with an unbootable kernel, make sure that you restart, 
# go into GRUB by waiting to see the > LInux Mint or >Advanced Options prompts on screen
# then hit Advanced Options, then select a stable kernel that worked last time, like 
# 6.8.0-51-generic
# use the latest config-* (default kernel config for Linux Mint) that you have :)

# I'm using `make` instead `make -j8` or whatever number after j, to ensure
# that multi-core kernel compilation doesn't introudce subtle errors 
cp /boot/config-$(uname -r) ./config ~/linux-stable/.config
cd ~/linux-stable
# check the config to make sure it copied over correctly, and looks right
vim .config
make oldconfig
sudo apt-get install linux-firmware linux-source gcc libncurses-dev dpkg-devlibssl-dev debhelper-compat
make localmodconfig
sudo mkdir -p /usr/local/src/debian
# i ran this since i saw an error about SSL certs or some such
sudo cp -v /usr/src/linux-source-*/debian/canonical-*.pem /usr/local/src/debian/
sudo apt purge linux-source*
# ensure that you're in the directory where you cloned the linux kernel
scripts/config --disable SYSTEM_TRUSTED_KEYS
scripts/config --disable SYSTEM_REVOCATION_KEYS
make deb-pkg
sudo dpkg -i linux-*.deb
# if you're on bare metal, like i am, you can now remoot into your new Linux kernel
